language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
          env: PYVERSION=""
        - os: linux
          dist: precise
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: precise
          sudo: required
          python: 2.7
          env: PYVERSION=""

install:
    - pip${PYVERSION} install --upgrade pip setuptools wheel
    - pip${PYVERSION} install coveralls codecov
    - pip${PYVERSION} install --only-binary=numpy,scipy scipy
    - pip${PYVERSION} install scikit-learn
    - pip${PYVERSION} install git+https://github.com/natekupp/ffx

before_script:
    - export PYTHONPATH=$(pwd):$PYTHONPATH;

script:
  - coverage${PYVERSION} run --source ffx tests/x_square_test.py
  - python tests/test_sklearn_api.py

after_success:
  - coveralls
