language: python

jobs:
  include:
    - python: "2.7"
      env: NOVALIDATE=0
    - python: "3.5"
      env: NOVALIDATE=0
    - python: "3.6"
    - python: "3.7"

install:
  - pip install -r dev-requirements.txt
  - pip install -e .

before_script:
  - export PYTHONPATH=$(pwd):$PYTHONPATH;

script:
  - '[ -z "$NOVALIDATE" ] && make validate || echo "skipping validate"'
  - pytest --cov ffx

after_success:
  - coveralls
