language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r dev-requirements.txt
  - pip install -e .

before_script:
  - export PYTHONPATH=$(pwd):$PYTHONPATH;

script:
  - pytest --cov ffx

after_success:
  - coveralls
